{% set name = "SciFiReaders" %}
{% set version = "0.11.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44a7c34fd28d6e92c0f6186154f23d72d1adc6d2bffd50af57857785e70e7c9a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - dask-core >=2.20.0
    - numpy >=1.10
    - sidpy >=0.0.5
    - arm_pyart
    - pynsid
    - numba
    - finesse

test:
  imports:
    - SciFiReaders

about:
  home: https://github.com/pycroscopy/SciFiReaders
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for extracting data and metadata from scientific data files
  doc_url: https://pycroscopy.github.io/SciFiReaders/
  dev_url: https://github.com/pycroscopy/SciFiReaders

extra:
  recipe-maintainers:
    - ramav87
    - gduscher
    - ssomnath
