{% set name = "SciFiReaders" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccc54e7cc8e5bd61bb8c025c69753ca1b50733e94c31d2ea87dd64bc22c1351c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - cytoolz
    - dask-core >=2.20.0
    - numpy >=1.10
    - sidpy >=0.0.2
    - six
    - toolz

test:
  imports:
    - SciFiReaders

about:
  home: https://github.com/pycroscopy/SciFiReaders
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for extracting data and metadata from scientific data files
  doc_url: https://pycroscopy.github.io/SciFiReaders/
  dev_url: https://github.com/pycroscopy/SciFiReaders

extra:
  recipe-maintainers:
    - ramav87
    - gduscher
    - ssomnath
